import sharp from 'sharp'
import fs from 'fs'
import path from 'path'

const WIDTHS = [400, 800, 1200]
const JPEG_QUALITY = 80
const WEBP_QUALITY = 80
const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp'])

const MEDIA_SRC = path.resolve(import.meta.dirname, '../content/media')
const MEDIA_OUT = path.join(import.meta.dirname, '../public/media')
const MANIFEST_OUT = path.join(import.meta.dirname, '../src/content/generated/image-manifest.ts')

interface ManifestEntry {
  original: string
  new: string
  role?: string
  sourceUrl?: string
}

interface ImageInfo {
  fallback: string
  srcSet: string
  width: number
  height: number
}

async function main() {
  const manifestRaw = fs.readFileSync(path.join(MEDIA_SRC, 'manifest.json'), 'utf-8')
  const manifest: Record<string, ManifestEntry[]> = JSON.parse(manifestRaw)

  // Ensure output dirs
  fs.mkdirSync(MEDIA_OUT, { recursive: true })
  fs.mkdirSync(path.dirname(MANIFEST_OUT), { recursive: true })

  const imageManifest: Record<string, ImageInfo> = {}
  let processed = 0
  let skipped = 0

  for (const [slug, entries] of Object.entries(manifest)) {
    if (slug === '_unsorted') continue

    for (const entry of entries) {
      const ext = path.extname(entry.new).toLowerCase()
      if (!IMAGE_EXTENSIONS.has(ext)) {
        // Copy non-image files (PDFs) as-is
        const srcFile = path.join(MEDIA_SRC, entry.new)
        const outFile = path.join(MEDIA_OUT, entry.new)
        if (fs.existsSync(srcFile)) {
          fs.mkdirSync(path.dirname(outFile), { recursive: true })
          if (!fs.existsSync(outFile)) {
            fs.copyFileSync(srcFile, outFile)
          }
        }
        continue
      }

      const srcFile = path.join(MEDIA_SRC, entry.new)
      if (!fs.existsSync(srcFile)) {
        console.warn(`  MISSING: ${entry.new}`)
        continue
      }

      const outDir = path.join(MEDIA_OUT, path.dirname(entry.new))
      fs.mkdirSync(outDir, { recursive: true })

      const baseName = path.basename(entry.new, ext)
      const relativePath = entry.new

      // Check cache: skip if all outputs exist and are newer than source
      const srcStat = fs.statSync(srcFile)
      const fallbackOut = path.join(MEDIA_OUT, relativePath)
      const allOutputsExist = fs.existsSync(fallbackOut)

      if (allOutputsExist && fs.statSync(fallbackOut).mtimeMs > srcStat.mtimeMs) {
        skipped++
        // Still need metadata for manifest
        const meta = await sharp(srcFile).metadata()
        const w = meta.width ?? 0
        const h = meta.height ?? 0

        const srcSetParts: string[] = []
        for (const width of WIDTHS) {
          if (width <= w) {
            srcSetParts.push(`/media/${path.dirname(relativePath)}/${baseName}-${width}w.webp ${width}w`)
          }
        }

        imageManifest[relativePath] = {
          fallback: `/media/${relativePath}`,
          srcSet: srcSetParts.join(', '),
          width: w,
          height: h,
        }
        continue
      }

      try {
        const image = sharp(srcFile)
        const meta = await image.metadata()
        const w = meta.width ?? 0
        const h = meta.height ?? 0

        // Generate compressed fallback in original format
        if (ext === '.jpg' || ext === '.jpeg') {
          await sharp(srcFile).jpeg({ quality: JPEG_QUALITY }).toFile(fallbackOut)
        } else if (ext === '.png') {
          await sharp(srcFile).png({ compressionLevel: 9 }).toFile(fallbackOut)
        } else {
          await sharp(srcFile).webp({ quality: WEBP_QUALITY }).toFile(fallbackOut)
        }

        // Generate WebP at multiple widths
        const srcSetParts: string[] = []
        for (const width of WIDTHS) {
          if (width <= w) {
            const webpPath = path.join(outDir, `${baseName}-${width}w.webp`)
            await sharp(srcFile)
              .resize(width, undefined, { withoutEnlargement: true })
              .webp({ quality: WEBP_QUALITY })
              .toFile(webpPath)
            srcSetParts.push(`/media/${path.dirname(relativePath)}/${baseName}-${width}w.webp ${width}w`)
          }
        }

        imageManifest[relativePath] = {
          fallback: `/media/${relativePath}`,
          srcSet: srcSetParts.join(', '),
          width: w,
          height: h,
        }

        processed++
        console.log(`  OK: ${entry.new} (${w}x${h})`)
      } catch (err) {
        console.error(`  ERROR: ${entry.new}:`, err)
      }
    }
  }

  // Write TypeScript manifest
  const tsContent = `// Auto-generated by optimize-images.ts — do not edit
export interface ImageInfo {
  fallback: string
  srcSet: string
  width: number
  height: number
}

export const imageManifest: Record<string, ImageInfo> = ${JSON.stringify(imageManifest, null, 2)}
`
  fs.writeFileSync(MANIFEST_OUT, tsContent)

  console.log(`\nDone! Processed: ${processed}, Skipped (cached): ${skipped}, Total entries: ${processed + skipped}`)
}

main().catch(console.error)
